---
title: Ayo Isaiah
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: sudo@ayoisaiah.com
description: Software Developer and Writer
baseurl: ''
url: https://ayoisaiah.com
twitter_username: ayisaiah
github_username: ayoisaiah
sass:
  sass_dir: assets/sass
  style: :compressed
include:
- _pages
markdown: kramdown
kramdown:
  input: GFM
google_analytics: UA-74640522-1
paginate: 20
paginate_path: "/blog/page:num"
port: 4009
disqus: ayoisaiah
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-redirect-from
exclude:
- node_modules
- gulpfile.js

theme: jekyll-theme-leap-day